### ISSUE TITLE
Regressing from an RGB Image (Sec. 3 supplementary) vs method described in main paper (Sec. 3 main paper)

### ISSUE THREAD

**Issue by resindraburiza** [yufu-wang/aves#1]
Dear Yufu Wang,

First of all, I would like to thank you for sharing your work. It is very interesting work.
Though, I would like to ask about the difference between "Regressing from an RGB image" and the method described in the Section 3 in the main paper.

If I understand correctly, the method of "regressing from an RGB" takes only RGB images as input and outputs the AVES body model + translation using a single network (HMR-based) while the method described in the main paper takes keypoints + silhouette as input and output AVES body model + translation using MeshNet and further optimize it based on camera fitting and shape fitting loss. Is it correct? 
Is there any side to side comparison between the results of the two methods? It seems that the method detailed in the paper has better result since it has vertices deformation (dv in the paper?) and the "regressing from and RGB" does not have it. Is my understanding correct?
Also, do you plan to relase the pipeline of "Regressing from an RGB Image"? 
Thank you very much!

Best regards,
Resindra

**Comment by yufu-wang** [comment]
Hi Resindra, thanks for the kind words! Your understanding about "regressing from an RGB" is correct. However, the network in the main method only outputs pose parameters of the base model. The base model has no shape components and the main method is to learn a shape space. This step is simply to provide a better pose initialization for the optimization, and not comparable to the "regression from RGB". "Regression from and RGB" output pose parameters and the learned shape parameters. The optimization has better results because it has access to ground truth keypoints+silhouette, while regression is a predictive method. Hope this clear things up.

**Comment by resindraburiza** [comment]
Dear Yufu Wang,

thank you very much for your reply.
I see the difference now that the proposed optimization process has access to the ground truth key points and silhouette for the optimization process. Thank you very much for the clear explanation.

Best,
Resindra
